# Generated by Django 4.2.4 on 2023-08-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPulseira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=False)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='media/qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Pulseira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pulseira', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.codigopulseira')),
            ],
        ),
    ]
